---
name: OpenTofu Check

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
        description: AWS region to deploy to.
      account_id:
        required: true
        type: string
        description: AWS account ID to deploy to.
      role_name:
        required: false
        type: string
        description: Name of the IAM role for deployment.
        default: 'GithubActionsDeploymentRole'
      tf_working_dir:
        required: true
        type: string
        description: Directory containing the OpenTofu configuration files.

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.tf_working_dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: OpenTofu Setup
        uses: opentofu/setup-opentofu@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role_name }}
          role-session-name: GithubActions
          aws-region: ${{ inputs.aws_region }}

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Format
        id: fmt
        run: tofu fmt -check

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color
